# Implementing a Deep Neural Network

This notebook details the steps taken to implement a Deep Neural Network(DNN). To build our neural network, the libraies TensorFlow and Keras are leveraged in order to provide the features and methods required to build the components of a neural network.

TensorFlow: An open-source platform for the implementation, training, and deployment of machine learning models.
Keras: An open-source library used for the implementation of neural network architectures that run on both CPUs and GPUs.

## Installation

Installing Tensorflow and Keras is simple when using a package managers such as pip or conda.

Here are examples of installing TensorFlow.
And it's worth mentioning that you don’t need to explicitly install keras as it’s a built in API within TensorFlow 2+

If you have a CPU you can install TensorFlow with the following command
“conda install tensorflow”

If you have a GPU installed, you can install TensorFlow with the following command
“conda install tensorflow-gpu”

In [1]:
import tensorflow as tf
from tensorflow import keras

**You can verify a successful installation of TensorFlow in several ways**

1. Observing the TensorFlow package in your environment by running the command
“conda list”

2. Second is by importing TensorFlow into your notebook and checking the version programmatically
tf.version.VERSION


In [2]:
# Verifying installation of Tensorflow
tf.version.VERSION

'2.0.0'

As mentioned earlier Keras provides tools required to implement the classification model. 
Keras houses the Model API, which provides several methods, components and classes required to implement neural networks

The three various ways you can create keras Models are through the: Sequential model, Functional API and Model subclassing.
Today we will only be exploring the Sequential model method of implementing neural networks.

1. **The Sequential model**, which is very straightforward (a list of layers), but is limited to single-input, single-output stacks of layers (as the name gives away).
2. **The Functional API**, which is an easy-to-use, fully-featured API that supports arbitrary model architectures. For most people and most use cases, this is what you should be using. This is the Keras "industry strength" model.
3. **Model Subclassing**, where you implement everything from scratch on your own. Use this if you have complex, out-of-the-box research use cases.

## Neural Network Implementation Components

1. Keras Layers API (keras.layers)
Layers within Keras allow for the composition of neural networks as they are the fundemental components of neural networks in Keras.
Layers within Keras also house the following: weights of the neural network and functions that act upon inputs and provide outputs, typically to the next layer 

2. Flatten Layer (keras.layers.Flatten)
The Flatten class acts upon the inputs by reducing the dimensionality of the input data to one.
Image datasets are multidimensional, and in order for input data to be feed forward input data through the neural network the dimensions of the input data needs to be reduced to one, essentially we require our input data to be a 1-dimensional.
For example, an input to the Flatten layer with the shape (None, 10, 2) will provide the output (None, 20).

The input shape of the first layer of a neural network should match the shape of the input data, hence the 'input_shape' attribute of the Flatten layer is (28,28) when using the FashionMNIST dataset (shown in the notebook 02_image_classification_with_DNN).

3. Dense Layer (keras.layers.Dense)
The dense layer houses neurons within the neural network. the number of neurons within a dense layer is specified by the 'unit' attribute. All neurons/units within the dense layer receives input from the previous layer.
The dense layer operation on its input is a matrix vector muliplication between the input data, learnable weights of the layer and biases.

4. Activation Functions (keras.activations.relu / keras.activations.softmax)
Activation Function: A mathematical operation that transforms the result or signals of neurons into a normalized output. An activation function is a component of a neural network that introduces non-linearity within the network. The inclusion of the activation function enables the neural network to have greater representational power and solve complex functions.

**Examples of Activation functions**
ReLU activation: Stands for ‘rectified linear unit’ ( y=max(0, x)). It’s a type of activation function that transforms the value results of a neuron. The transformation imposed by ReLU on values from a neuron is represented by the formula y=max(0,x). The ReLU activation function clamps down any negative values from the neuron to 0, and positive values remain unchanged. The result of this mathematical transformation is utilized as the output of the current layer, and as input to the next.

Softmax: An activation function that is utilized to derive the probability distribution of a set of numbers within an input vector. The output of a softmax activation function is a vector in which its set of values represents the probability of an occurrence of a class/event. The values within the vector all add up to 1.


**Below is a deep neural network, containing three hidden layer, an input layer and one output layer and it's built using the Keras Sequential API.**

In [3]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28,28]),
    keras.layers.Dense(500, activation=keras.activations.relu),
    keras.layers.Dense(250, activation=keras.activations.relu),
    keras.layers.Dense(100, activation=keras.activations.relu),
    keras.layers.Dense(10, activation=keras.activations.softmax)
])

2021-09-20 20:57:00.696056: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-20 20:57:00.697741: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.


## Neural Network Structural Information

A structural summary of the neural network implemented above is obtainable by calling the ‘summary’ method available on our model. By calling the summary method, we gain information on the model properties such as layers, layer type, shapes, number of weights in the model, and layers.

[Keras documentation reference](https://keras.io/api/models/model/#summary-method)

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 500)               392500    
_________________________________________________________________
dense_1 (Dense)              (None, 250)               125250    
_________________________________________________________________
dense_2 (Dense)              (None, 100)               25100     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1010      
Total params: 543,860
Trainable params: 543,860
Non-trainable params: 0
_________________________________________________________________


Conducting analysis on a neural network internal components is useful in machine learning, especially when you are not the creator of the neural network.
Keras has provided several methods of getting the interal details of an already built neural network.

1. Using the python's list subscript functionality.
2. Using the Keras's 'get_layers' method.

How to implement and use both methods of getting neural network information are shown below. In the next code snippets we are analysing the weights and baises of the second layer (first hidden layer) of the neural network implemented above.

In [12]:
first_hidden_layer = model.layers[1]
weights, biases = first_hidden_layer.weights
print(weights)
print('\n')
print(biases)

<tf.Variable 'dense/kernel:0' shape=(784, 500) dtype=float32, numpy=
array([[ 0.05093002,  0.05504215,  0.05177955, ...,  0.02047996,
        -0.0625891 , -0.00962639],
       [ 0.06531806, -0.0597941 ,  0.04932003, ..., -0.01232168,
        -0.06414726,  0.01078124],
       [-0.01519692, -0.01787981, -0.04564763, ..., -0.0055357 ,
        -0.04718521,  0.01353937],
       ...,
       [-0.05444261,  0.01340163,  0.03171267, ...,  0.01427417,
        -0.04084084,  0.02765889],
       [ 0.02220616, -0.01719176,  0.02869142, ...,  0.02767232,
        -0.03098669, -0.01445924],
       [ 0.03595876, -0.03129721,  0.03073858, ..., -0.05191932,
        -0.00325928, -0.04973669]], dtype=float32)>


<tf.Variable 'dense/bias:0' shape=(500,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0

In [13]:
layer = model.get_layer(index=1)
print(layer.weights)
print('\n')
print(layer.bias)

[<tf.Variable 'dense/kernel:0' shape=(784, 500) dtype=float32, numpy=
array([[ 0.05093002,  0.05504215,  0.05177955, ...,  0.02047996,
        -0.0625891 , -0.00962639],
       [ 0.06531806, -0.0597941 ,  0.04932003, ..., -0.01232168,
        -0.06414726,  0.01078124],
       [-0.01519692, -0.01787981, -0.04564763, ..., -0.0055357 ,
        -0.04718521,  0.01353937],
       ...,
       [-0.05444261,  0.01340163,  0.03171267, ...,  0.01427417,
        -0.04084084,  0.02765889],
       [ 0.02220616, -0.01719176,  0.02869142, ...,  0.02767232,
        -0.03098669, -0.01445924],
       [ 0.03595876, -0.03129721,  0.03073858, ..., -0.05191932,
        -0.00325928, -0.04973669]], dtype=float32)>, <tf.Variable 'dense/bias:0' shape=(500,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0